import Footer from "./(Components)/Footer/Footer";
import Navbar from "./(Components)/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Virtual Reality",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
